### ISSUE TITLE
Cannot read property 'initialize' of undefined

### ISSUE THREAD

**Issue by jayesbe** [Heartnett/electron-aware#25]
I would really love to use this package but I am getting the above error when trying to initialize the browser side

```
const aware = require('electron-aware/server');
const awareClient = aware.initialize(window);
awareClient.on('test-event-ok', (args) => {
});
```

**Comment by Heartnett** [comment]
Sorry for the late response. **This project is deprecated.**
Please have a look at these NPM packages:

- https://www.npmjs.com/package/electron-nokogiri
- https://www.npmjs.com/package/electron-ipcrenderer-websocket
- https://www.npmjs.com/package/electron-ipc-socket
- https://www.npmjs.com/package/electron-event-dispatcher
- https://www.npmjs.com/package/electron-ipc-proxy
